version: '3'

services:
  elastic:
    image: ghcr.io/prathamadh/prashnakhoj:v1
       
  backend:
    build: ./backend
    # volumes:
    #   - ./backend/:/backend/
    #   - /backend/node_modules
    depends_on:
      - elastic

  frontend:
    build: ./frontend
    # volumes:
    #   - ./frontend/:/frontend/
    #   - /frontend/node_modules
    depends_on:
      - backend

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - frontend
 
